# Generated by Django 2.0.3 on 2018-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealrecommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
